# <<directions>> == any of {N S W E North South West East L R U D Left Right Up Down}

# these settings apply to anything that starts with `app.`
[app.*.*]
# default: false, must be set to true to enable integration
enabled = bool
# default: false, if set to true, this program cannot move the app window (but it can still move internal windows if move.internal_panes = true)
anchor_app_window = bool

# default: true, allow to "popout" the pane, aka "move pane into new window"
move.docking.tear_off = bool

# default: true, allow to merge the pane back into the app window, aka "move pane into other window"
move.docking.snap_back = bool


# these settings are browser specific (apply to anything that starts with `app.browser.`)
[app.browser.*]
focus.{left,right,up,down} = "ignore" | "previous_tab" | "next_tab" | "first_tab" | "last_tab"
move.{left,right,up,down} = "ignore" | "backward" | "forward" | "to_first_position" | "to_last_position"
# default: true, in order to popout the pane, it's longest edge must stick to the edge of app window
move.docking.tear_off.only_if_tab_is_first_or_last = bool


# these settings are terminal and editor specific (apply to anything that starts with `app.terminal.` or `app.editor`)
[app.(terminal|editor).*]
# default: true, if set to false, focusing internal panes wont work, and WM will focus next window on the desktop
focus.internal_panes = bool 

# default: true, if set to false, focusing internal panes wont work, and WM will focus next window on the desktop
focus.internal_panes = bool 

# default: NWSE, focus.internal_panes must be true. Limits the directions is which we can change focus internally,
# Trying to change focus in direction not configured for, will result in WM focusing next window on the desktop in that direction
focus.internal_panes.allowed_directions = <<directions>>

# default: true, if set to false, resizing internal panes wont work, and WM will resize currently focused window
resize.internal_panes = bool

# default: NWSE, resize.internal_panes must be true. Limits the directions is which we can resize internal panes,
# Trying to resize in direction not configured for, will result in WM resizing the currently focused window in that direction.
resize.internal_panes.allowed_directions = <<directions>>

# default: true, if set to false, moving internal panes wont work, and WM will move currently focused app window instead
move.internal_panes = bool

# default: NWSE, move.internal_panes must be true. Limits the directions is which we can move internal panes,
# Trying to move in direction not configured for, will result in WM moving the currently focused window in that direction.
move.internal_windows_allowed_directions = <<directions>>

# default: true, allow to "popout" the pane, aka "move pane into new window"
move.docking.tear_off = bool

# default: true, in order to popout the pane, it's longest edge must stick to the edge of app window
move.docking.tear_off.only_if_edgemost = true

# default: true, allow to merge the pane back into the app window, aka "move pane into other window"
move.docking.snap_back = bool

[app.terminal.*]
# default: true, if set to false, will go to next tab once you try to focus right while right-edgemost-pane is active
focus.ignore_tabs = bool

# default: true, if set to false, will move current pane to next tab if you try to move right while right-edgemost-pane is active
move.ignore_tabs = bool

# default: "mux_pane"
move.docking.tear_off.scope = "mux_pane" | "mux_window" | "mux_session" | "terminal_tab"

# wezterm specific settings
[app.terminal.wezterm]
# default: "wezterm"
mux_backend = "tmux" | "zellij" | "wezterm" | none

# kitty specific settings
[app.terminal.kitty]
# default: "kitty"
mux_backend = "tmux" | "zellij" | "kitty" | none

# iterm2 specific settings
[app.terminal.iterm2]
# default: "tmux"
mux_backend = "tmux" | "zellij" 

[app.editor.emacs]
# default: "emacs_buffer", .... self explanatory hopefully xD
move.docking.tear_off.scope = "emacs_buffer" | "emacs_window" | "emacs_workspace"

[app.editor.vscode]
# default: "vscode_buffer", .... self explanatory hopefully xD
move.docking.tear_off.scope = "vscode_buffer" | "vscode_editor_group" 

[app.editor.neovim]
# default: "neovim_buffer", .... self explanatory hopefully xD
move.docking.tear_off.scope = "neovim_buffer" | "neovim_pane" 


###
# only one wm. can be enabled at a given time
###

[wm.niri]
enabled = bool

[wm.yabai]
enabled = bool

[wm.aerospace]
enabled = bool
